ERROR - 2022-02-21 01:14:10 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-02-21 01:14:10 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp2\htdocs\resto\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp2\htdocs\resto\system\Database\BaseBuilder.php(1484): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', NULL, false)
#2 C:\xampp2\htdocs\resto\app\Models\UserModel.php(56): CodeIgniter\Database\BaseBuilder->countAll()
#3 C:\xampp2\htdocs\resto\app\Controllers\Home.php(72): App\Models\UserModel->jumlahUser()
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\Home->home()
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-02-21 01:14:10 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp2\htdocs\resto\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp2\\htdoc...', 96, Array)
#1 C:\xampp2\htdocs\resto\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(234): include('C:\\xampp2\\htdoc...')
#3 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-21 02:19:03 --> Class 'Tests\Support\Models\UserModel' not found
#0 C:\xampp2\htdocs\resto\system\CodeIgniter.php(802): App\Controllers\Login->__construct()
#1 C:\xampp2\htdocs\resto\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#5 {main}
CRITICAL - 2022-02-21 02:27:04 --> Undefined variable: title
#0 C:\xampp2\htdocs\resto\app\Views\login\index.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp2\\htdoc...', 14, Array)
#1 C:\xampp2\htdocs\resto\system\View\View.php(210): include('C:\\xampp2\\htdoc...')
#2 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('Login/index', Array, true)
#4 C:\xampp2\htdocs\resto\app\Controllers\Login.php(21): view('Login/index')
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\Login->index()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#7 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#10 {main}
CRITICAL - 2022-02-21 02:27:57 --> Call to undefined function form_open()
#0 C:\xampp2\htdocs\resto\system\View\View.php(210): include()
#1 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('Login/index', Array, true)
#3 C:\xampp2\htdocs\resto\app\Controllers\Login.php(21): view('Login/index', Array)
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\Login->index()
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
